version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.32
    container_name: main_prisma
    restart: unless-stopped
    ports:
      - '4467:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: dev
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            database: prisma
  postgres:
    image: postgres:10.3
    container_name: main_postgres
    restart: unless-stopped
    ports:
    - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
